config/routes.rb
Rails.application.routes.draw do
 root 'store#index', as: 'store_index'
 
  devise_for :users
 resources :products

 resources :items
 resources :carts
 resources :orders
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	has_many :items, dependent: :destroy

	def add_product(product)
		current_item = items.find_by(product_id: product.id)
		if current_item
			current_item.quantity += 1
		else
			current_item = items.build(product_id: product.id)
		end
		current_item
	end

	def total_price
		items.to_a.sum {|item| item.total_price}
	end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :product, optional: true
  belongs_to :cart

  def total_price
  	product.price * quantity
  end
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :items, dependent: :destroy

	enum foundation: {
		"Fundacja Dziecięca Fantazja"			=>0,
		"Miłosnicy zwierząt pomagają"			=>1,
		"Ratujmy Puszczę"						=>2,
		"Pomoc Polakom poza Polską"				=>4,
		"Wspieram młodych programistów"			=>5,
		"Ruby on Rails is coming foundation"	=>6
	}
	
    validates :name, :address, :email, presence: true
	validates :foundation, inclusion: foundations.keys


	# def add_items_from_cart(cart)
	# 	cart.items.each do |item|
	# 		item.cart_id = nil
	# 		items << item
	# 	end
	# end

	def add_sellers_items_from_cart(items, seller)
  		sellers_items = items.select {|item| item.product.user_id == seller}
		sellers_items.each do |item|
			item.cart_id = nil
			items << item
		end
	end
end

app/models/product.rb
class Product < ApplicationRecord
	validates :title, :description, presence: true
	validates :price, numericality: { greater_than_or_equal_to: 0.01 }
	validates :title, uniqueness: true
	belongs_to :user
	has_many :items
	before_destroy :ensure_not_referenced_by_any_item

	private

	# ensure that there are no line items referencing this product
	def ensure_not_referenced_by_any_item
		unless items.empty?
			errors.add(:base, 'Na stanie są sztuki tego produktu')
			throw :abort
		end
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	before_action :set_cart, only: [:show, :edit, :update, :destroy]
	rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
	
	def show
		@cart = Cart.find(params[:id])
	end

	def destroy
      @cart.destroy if @cart.id == session[:cart_id]
      session[:cart_id] == nil
	  redirect_to store_index_url
	end

	private

	def invalid_cart
		logger.error "Wybrany koszyk nie istnieje"
		redirect_to store_index_url, notice: 'Niewłaściwy koszyk'
	end

	def set_cart
      @cart = Cart.find(params[:id])
    end
end

app/controllers/concerns/current_cart.rb
module CurrentCart

	private

	  def set_cart
	  	@cart = Cart.find(session[:cart_id])
	  rescue ActiveRecord::RecordNotFound
	  	@cart = Cart.create
	  	session[:cart_id] = @cart.id
	  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  include CurrentCart
  before_action :set_cart, only: [:create, :destroy]
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_item

  def index
	@items = Item.all
  end

  def show
  end

  def new
	@item = Item.new
  end

  def edit
  end

  def create
	  product = Product.find(params[:product_id])
	  @item = @cart.add_product(product)

    respond_to do |format|
	    if @item.save
		    format.html { redirect_to store_index_url }
        format.js { @current_item = @item }
	    else
		    render :new
      end
	  end
  end

  def update
    if @item.update(item_params)
      redirect_to @item,
        notice: 'Towar został zaktualizowany.' 
    else
      render :edit 
    end
  end

  def destroy
    if @item.quantity > 1
      @item.quantity -=1
      @item.save
      respond_to do |format|
        format.html 
        format.js { @current_item = @item }
      end
    else
      @item.destroy
      respond_to do |format|
        format.html 
        format.js 
      end
    end
    redirect_to store_index_url
  end

  private

  def set_item
	  @item = Item.find(params[:id])
  end

  def item_params
	  params.require(:item).permit(:product_id)
  end

  def invalid_item
      logger.error "Towar nie istnieje"
      redirect_to store_index_url, notice: 'Wybrany towar nie istnieje'
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	include CurrentCart
	before_action :set_cart, only: [:new, :create]
	before_action :ensure_cart_isnt_empty, only: :new
	before_action :set_order, only:[:show, :ipdate, :edit, :destroy]

	def new
		@order = Order.new
	end

    def create
  	  @items = @cart.items
  	  sellers = (@items.map {|item| item.product.user_id}).uniq
  	  sellers.each do |seller|
  		  @order = Order.new(order_params)
          @order.add_sellers_items_from_cart(@items, seller)
          @order.save
          OrderMailer.received(@order).deliver_now
          if seller == sellers.last
            Cart.destroy(session[:cart_id])
            session[:cart_id] = nil
            redirect_to store_index_url, notice: 'Dzięki za złożenie zamówienia.'
          end
      end
    end
    
	private

	def set_order
	  @order = Order.find(params[:id])
	end

    def order_params
      params.require(:order).permit(:name, :address, :email, :foundation)
    end

	def ensure_cart_isnt_empty
      if @cart.items.empty?
        redirect_to store_index_url, notice: 'Twój koszyk jest pusty.'
      end
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_action :set_product, only: [:show, :update, :edit, :destroy]
	rescue_from ActiveRecord::RecordNotFound, with: :invalid_product

	def index
		@products = Product.order("created_at DESC")
	end

	def show
	end

	def new
		@product = current_user.products.build
	end

	def create
		@product = current_user.products.build(product_params)

		if @product.save
			redirect_to @product, notice: "Produkt został wystawiony na sprzedaż."
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @product.update(product_params)
			redirect_to @product, notice: "Produkt został zaktualizowany."

			@products = Product.all
			ActionCable.server.broadcast 'products',
			  html: render_to_string('store/index', layout: false)
		else
			render 'edit'
		end
	end

	def destroy
		@product.destroy
		redirect_to products_path
	end

	private

	def set_product
		@product = Product.find(params[:id])
	end

	def product_params
		params.require(:product).permit(:title, :description, :price)
	end
	
	def invalid_product
      logger.error "Produkt nie istnieje"
      redirect_to store_index_url, notice: 'Wybrano niewłaściwy produkt'
    end


end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  include CurrentCart
  before_action :set_cart
  def index
  	@products = Product.order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def hidden_div_if(condition, attributes = {}, &block)
		if condition
			attributes["style"] = "display: none"
		end
		content_tag("div", attributes, &block)
	end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/carts/_cart.html.haml
%h2 Koszyk
%table
  = render(cart.items)
  %tr.total_line
    %td.total{:colspan => "2"} Total
    %td.total_cell= number_to_currency(cart.total_price)
#button= button_to "Kupuję", new_order_path, method: :get 
#button= button_to 'Opróżnij koszyk', cart, method: :delete, data: {confirm: 'Na pewno?'}

app/views/carts/show.html.haml
- if @cart.items.empty?
  %h2 Twój koszyk jest pusty. Czas na zakupy!
- else
  = render @cart

app/views/items/_item.html.haml
%tr{class: ("current_item" if item == @current_item)}
  %td
    = item.quantity
    &times;
  %td= item.product.title
  %td.item_price= number_to_currency(item.total_price)
  %td.remove_item= button_to 'Usuń', item, method: :delete, remote: true 

app/views/items/_item.text.haml
= sprintf("%2d x %s", item.quantity,  
  truncate(item.product.title, length: 50)) 

app/views/items/create.js.erb
$('#notice').hide();   //<--- need fixed

if($('#cart tr').length == 1) { $('#cart').show('blind', 1000); }

$('#cart').html("<%=j render(@cart) %>");

$('.current_item').css({'background-color': 'white'}).
  animate({'background-color': '#999999'}, 1000);

app/views/items/destroy.js.erb
$('#cart').html("<%=j render(@cart) %>");

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Charity Store
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body{:class => "#{controller.controller_name}"}
    #navbar
      - if user_signed_in?
        = link_to "Wyloguj", destroy_user_session_path, method: :delete
        = link_to "Moje konto"
      - else
        = link_to "Zaloguj", new_user_session_path
        = link_to "Załóż konto", new_user_registration_path
    - flash.each do |name, msg|
      = content_tag :div, msg, class: "alert alert-info"
    #columns
      #side
        #cart
          - if @cart
            = hidden_div_if(@cart.items.empty?, id: 'cart') do
              = render @cart
        / %ul
        /   %li
        /     %a= link_to 'Pierwszy'
        /   %li
        /     %a= link_to 'Drugi'
        /   %li
        /     %a= link_to 'Trzeci'
      #main
        = yield

app/views/orders/_form.html.haml
= form_for(order) do |f|
  - if order.errors.any?
    #error_explanation
      %h2= raw t('errors.template.header', count: @order.errors.count, model: t('activerecord.models.order'))
      %p= t('errors.template.body')
      %ul
        - order.errors.full_messages.each do |message|
          %li= raw message
  .field
    = f.label :name, t('.name')
    = f.text_field :name, size: 40
  .field
    = f.label :address, t('.address_html')
    = f.text_area :address, rows: 3, cols: 40
  .field
    = f.label :email, t('.email')
    = f.text_field :email, size: 40
  .field
    = f.label :foundation, t('.foundation')
    = f.select :foundation, Order.foundations.keys, prompt: 'Wybierz fundację'
  .actions
    = f.submit 'Zamów'

app/views/orders/new.html.haml
.depot_form
  %fieldset
    %legend Wprowadź swoje dane
    = render 'form', order: @order

app/views/products/_form.html.haml
= simple_form_for @product, html: { multipart: true } do |f|
  - if @product.errors.any?
    #errors
      %h2
      = pluralize(@product.errors.count, "error")
      prevented this Product from saving
      %ul
        - @product.errors.full_messages.each do |msg|
          %li= msg
  
  .form-group
    = f.input :title, input_html: { class: 'form-control'}

  .form-group
  = f.input :description, input_html: { class: 'form-control'}

  .form-group
  = f.input :price, input_html: { class: 'form-control'}

  = f.button :submit, class: "btn btn-primary"

app/views/products/edit.html.haml
%h1 Edytuj Produkt

= render 'form'

= link_to "Powrót", products_path

app/views/products/index.html.haml
= link_to "Dodaj produkt", new_product_path
%table
- @products.each do |product|
  %tr{:class =>  cycle('list_line_odd', 'list_line_even')}
    %td{:class =>  'list_description'}
      %h3= link_to product.title, product
      %p= sanitize(product.description)
      %p= number_to_currency(product.price)
    %td{:class => 'list_actions'}
      = link_to 'Show', product
      = link_to 'Edit', edit_product_path(product)
      = link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } 

app/views/products/new.html.haml
%h1 Nowy Produkt

= render 'form'

= link_to "Powrót", products_path

app/views/products/show.html.haml
%h2= @product.title
%p= @product.description
%p= @product.price
%p= @product.user.email

= link_to 'Powrót', products_path
= link_to 'Edytuj', edit_product_path
= link_to 'Usuń', product_path, method: :delete, data: {confirm: "Uzunąć produkt?"}

app/views/store/index.html.haml
%h1= "Produkty w Charity Store [Strona w budowie]"
- @products.each do |product|
  .entry
    %h3= link_to product.title, product
    %p= sanitize(product.description)
    .price_line
      #span{:class => "price"}
        = number_to_currency(product.price)
      = button_to 'Dodaj do koszyka', items_path(product_id: product),remote: true